apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: ap-northeast-2
  tags:
    environment: devel

vpc:
  cidr: "10.10.0.0/16" #"192.168.0.0/16"
  nat:
    gateway: Single

availabilityZones:
  - ap-northeast-2a
  - ap-northeast-2b
  - ap-northeast-2c

nodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 2
    volumeType: gp2
    volumeSize: 10
    privateNetworking: true
    ssh:
      enableSsm: true

managedNodeGroups:
  - name: management
    instanceType: t3.small
    minSize: 1
    desiredCapacity: 1
    maxSize: 2
    volumeType: gp2
    volumeSize: 30
    ssh:
      enableSsm: true
    availabilityZones: ["ap-northeast-2a","ap-northeast-2b","ap-northeast-2c"]

cloudWatch:
  clusterLogging:
    enableTypes:
      - api
      - audit
      - authenticator      