# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "k8s-m1" do |ubuntu|
    ubuntu.vm.box = "ubuntu/focal64"
    ubuntu.vm.hostname = "k8s-m1"
    ubuntu.vm.network "private_network", ip: "192.168.201.11"
    ubuntu.vm.provider "virtualbox" do |vb|
      vb.name   = "k8s-m1"
      vb.cpus   = 2
      vb.memory = 2048
    end
  end

  config.vm.provision "shell", path: "script.sh"
end